"""Add dose_value column to Medication model

Revision ID: 1bc7028088ae
Revises: e4718cc9040b
Create Date: 2024-02-22 23:04:21.252527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc7028088ae'
down_revision = 'e4718cc9040b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dose_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dose_unit', sa.String(length=10), nullable=True))
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('batch_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.DATE(), nullable=True))
        batch_op.drop_column('dose_unit')
        batch_op.drop_column('dose_value')

    # ### end Alembic commands ###
